test_that("compare_models returns loo comparison", {
  skip_if_no_cmdstan()
  skip_on_cran()
  config1 <- make_test_config(structural = "independent")
  config2 <- make_test_config(structural = "correlated")
  sim <- simulate_responses(config2, n_students = 200, seed = 42)
  r1 <- fit_model(sim$responses, config1, chains = 2, iter_warmup = 200, iter_sampling = 200)
  r2 <- fit_model(sim$responses, config2, chains = 2, iter_warmup = 200, iter_sampling = 200)
  comp <- compare_models(independent = r1, correlated = r2)
  expect_s3_class(comp, "tbl_df")
  expect_true("model" %in% names(comp))
  expect_true("elpd_diff" %in% names(comp))
})

test_that("flag_problem_items returns tibble with correct columns", {
  skip_if_no_cmdstan()
  skip_on_cran()
  config <- make_test_config()
  sim <- simulate_responses(config, n_students = 100, seed = 42)
  result <- fit_model(sim$responses, config, chains = 2, iter_warmup = 200, iter_sampling = 200)
  flagged <- flag_problem_items(result)
  expect_s3_class(flagged, "tbl_df")
  expect_true(all(c("obs_id", "pareto_k") %in% names(flagged)))
})

test_that("format_reflection_prompt returns character string", {
  skip_if_no_cmdstan()
  skip_on_cran()
  config <- make_test_config()
  sim <- simulate_responses(config, n_students = 100, seed = 42)
  result <- fit_model(sim$responses, config, chains = 2, iter_warmup = 200, iter_sampling = 200)
  prompt <- format_reflection_prompt(result, items = make_test_items())
  expect_type(prompt, "character")
  expect_true(nchar(prompt) > 100)
})
